### ISSUE TITLE
always version v1.0.0

### ISSUE THREAD

**Issue by stefanodesimone** [bitshifted/git-auto-semver#8]
Hi,
in my action i have:

   `- name: calculate version

      id: calculate-version  
      uses: bitshifted/git-auto-semver@v1
      with:
          main_branch: master
          create_tag: true
          tag_prefix: 'v'
    - name: Use version
      run: echo 'Calculated version:' ${{ steps.calculate-version.outputs.version-string }}`

First time a tag v1.0.0 was created, but if I commit a "fix" or  a "feat" message like "feat: add new method" version always is v1.0.0
Any suggestion?
Thanks
Stefano

**Comment by vdjurovic** [comment]
Sorry for late reply. The problem is most probably fetch depth in checkout action. Something like this should work:
```
- name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
```
Adding `fetch-depth` and `fetch-tags` pulls all required data.
